import {
  Backpack,
  Battery,
  BatteryCharging,
  Blocks,
  BookOpen,
  Calculator,
  Camera,
  Coffee,
  CookingPot,
  Cpu,
  Dices,
  Dumbbell,
  Footprints,
  Gamepad2,
  GlassWater,
  Glasses,
  Gift,
  HardDrive,
  Headphones,
  Joystick,
  Keyboard,
  Laptop,
  Monitor,
  Mouse,
  Notebook,
  NotebookPen,
  PenTool,
  Pencil,
  Router,
  Shirt,
  Smartphone,
  Speaker,
  Tablet,
  Tent,
  ToyBrick,
  Utensils,
  Watch,
  Bike,
  Package,
  type LucideIcon,
} from "lucide-react";
import type { ProductIconKey } from "@/lib/types";

export const productIcons: Record<ProductIconKey, LucideIcon> = {
  Headphones,
  Speaker,
  Mouse,
  Keyboard,
  Laptop,
  Monitor,
  Smartphone,
  Tablet,
  Watch,
  Camera,
  Gamepad2,
  Joystick,
  Backpack,
  BookOpen,
  Pencil,
  PenTool,
  Calculator,
  Notebook,
  NotebookPen,
  Shirt,
  Footprints,
  Glasses,
  Dumbbell,
  Tent,
  Bike,
  ToyBrick,
  Dices,
  Coffee,
  CookingPot,
  Utensils,
  Blocks,
  Cpu,
  HardDrive,
  Battery,
  BatteryCharging,
  Router,
  GlassWater,
  Gift,
};

/**
 * Fallback for an icon key that isn't a known entry (stale localStorage
 * data, bad input, anything) - use as `productIcons[icon] ||
 * DEFAULT_PRODUCT_ICON` at the call site (a plain object lookup, not a
 * function call) so React's static-components check still recognizes the
 * JSX tag as stable. Without a fallback, `undefined` reaching `<Icon />`
 * crashes render entirely.
 */
export const DEFAULT_PRODUCT_ICON: LucideIcon = Package;
